export const countries = [
    { value: 'Afghanistan', label: 'Afghanistan', callingCode: '+93', pattern: '^\\d{9}$' },
    { value: 'Albania', label: 'Albania', callingCode: '+355', pattern: '^\\d{8,9}$' },
    { value: 'Algeria', label: 'Algeria', callingCode: '+213', pattern: '^\\d{8,9}$' },
    { value: 'Andorra', label: 'Andorra', callingCode: '+376', pattern: '^\\d{6}$' },
    { value: 'Angola', label: 'Angola', callingCode: '+244', pattern: '^\\d{9}$' },
    { value: 'Argentina', label: 'Argentina', callingCode: '+54', pattern: '^\\d{10}$' },
    { value: 'Armenia', label: 'Armenia', callingCode: '+374', pattern: '^\\d{8}$' },
    { value: 'Australia', label: 'Australia', callingCode: '+61', pattern: '^\\d{9}$' },
    { value: 'Austria', label: 'Austria', callingCode: '+43', pattern: '^\\d{10}$' },
    { value: 'Azerbaijan', label: 'Azerbaijan', callingCode: '+994', pattern: '^\\d{9}$' },
    { value: 'Bahrain', label: 'Bahrain', callingCode: '+973', pattern: '^\\d{8}$' },
    { value: 'Bangladesh', label: 'Bangladesh', callingCode: '+880', pattern: '^\\d{10}$' },
    { value: 'Belarus', label: 'Belarus', callingCode: '+375', pattern: '^\\d{9}$' },
    { value: 'Belgium', label: 'Belgium', callingCode: '+32', pattern: '^\\d{9}$' },
    { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', callingCode: '+387', pattern: '^\\d{8}$' },
    { value: 'Brazil', label: 'Brazil', callingCode: '+55', pattern: '^\\d{10,11}$' },
    { value: 'Bulgaria', label: 'Bulgaria', callingCode: '+359', pattern: '^\\d{9}$' },
    { value: 'Cambodia', label: 'Cambodia', callingCode: '+855', pattern: '^\\d{8,9}$' },
    { value: 'Canada', label: 'Canada', callingCode: '+1', pattern: '^\\d{10}$' },
    { value: 'Chile', label: 'Chile', callingCode: '+56', pattern: '^\\d{9}$' },
    { value: 'China', label: 'China', callingCode: '+86', pattern: '^\\d{11}$' },
    { value: 'Colombia', label: 'Colombia', callingCode: '+57', pattern: '^\\d{10}$' },
    { value: 'Croatia', label: 'Croatia', callingCode: '+385', pattern: '^\\d{8,9}$' },
    { value: 'Cyprus', label: 'Cyprus', callingCode: '+357', pattern: '^\\d{8}$' },
    { value: 'Czech Republic', label: 'Czech Republic', callingCode: '+420', pattern: '^\\d{9}$' },
    { value: 'Denmark', label: 'Denmark', callingCode: '+45', pattern: '^\\d{8}$' },
    { value: 'Egypt', label: 'Egypt', callingCode: '+20', pattern: '^\\d{10}$' },
    { value: 'Estonia', label: 'Estonia', callingCode: '+372', pattern: '^\\d{7,8}$' },
    { value: 'Ethiopia', label: 'Ethiopia', callingCode: '+251', pattern: '^\\d{9}$' },
    { value: 'Finland', label: 'Finland', callingCode: '+358', pattern: '^\\d{9,10}$' },
    { value: 'France', label: 'France', callingCode: '+33', pattern: '^\\d{9}$' },
    { value: 'Georgia', label: 'Georgia', callingCode: '+995', pattern: '^\\d{9}$' },
    { value: 'Germany', label: 'Germany', callingCode: '+49', pattern: '^\\d{10}$' },
    { value: 'Ghana', label: 'Ghana', callingCode: '+233', pattern: '^\\d{9}$' },
    { value: 'Greece', label: 'Greece', callingCode: '+30', pattern: '^\\d{10}$' },
    { value: 'Greenland', label: 'Greenland', callingCode: '+299', pattern: '^\\d{6}$' },
    { value: 'Hungary', label: 'Hungary', callingCode: '+36', pattern: '^\\d{9}$' },
    { value: 'Iceland', label: 'Iceland', callingCode: '+354', pattern: '^\\d{7}$' },
    { value: 'India', label: 'India', callingCode: '+91', pattern: '^\\d{10}$' },
    { value: 'Indonesia', label: 'Indonesia', callingCode: '+62', pattern: '^\\d{9,10}$' },
    { value: 'Iraq', label: 'Iraq', callingCode: '+964', pattern: '^\\d{10}$' },
    { value: 'Ireland', label: 'Ireland', callingCode: '+353', pattern: '^\\d{9}$' },
    { value: 'Israel', label: 'Israel', callingCode: '+972', pattern: '^\\d{9}$' },
    { value: 'Italy', label: 'Italy', callingCode: '+39', pattern: '^\\d{9,10}$' },
    { value: 'Japan', label: 'Japan', callingCode: '+81', pattern: '^\\d{10}$' },
    { value: 'Jordan', label: 'Jordan', callingCode: '+962', pattern: '^\\d{9}$' },
    { value: 'Kazakhstan', label: 'Kazakhstan', callingCode: '+7', pattern: '^\\d{10}$' },
    { value: 'Kenya', label: 'Kenya', callingCode: '+254', pattern: '^\\d{9}$' },
    { value: 'Kiribati', label: 'Kiribati', callingCode: '+686', pattern: '^\\d{5}$' },
    { value: 'Kosovo', label: 'Kosovo', callingCode: '+383', pattern: '^\\d{8}$' },
    { value: 'Kuwait', label: 'Kuwait', callingCode: '+965', pattern: '^\\d{8}$' },
    { value: 'Kyrgyzstan', label: 'Kyrgyzstan', callingCode: '+996', pattern: '^\\d{9}$' },
    { value: 'Laos', label: 'Laos', callingCode: '+856', pattern: '^\\d{9}$' },
    { value: 'Latvia', label: 'Latvia', callingCode: '+371', pattern: '^\\d{8}$' },
    { value: 'Lebanon', label: 'Lebanon', callingCode: '+961', pattern: '^\\d{7,8}$' },
    { value: 'Libya', label: 'Libya', callingCode: '+218', pattern: '^\\d{9}$' },
    { value: 'Liechtenstein', label: 'Liechtenstein', callingCode: '+423', pattern: '^\\d{7}$' },
    { value: 'Lithuania', label: 'Lithuania', callingCode: '+370', pattern: '^\\d{8}$' },
    { value: 'Luxembourg', label: 'Luxembourg', callingCode: '+352', pattern: '^\\d{8}$' },
    { value: 'Malaysia', label: 'Malaysia', callingCode: '+60', pattern: '^\\d{9,10}$' },
    { value: 'Malta', label: 'Malta', callingCode: '+356', pattern: '^\\d{8}$' },
    { value: 'Mexico', label: 'Mexico', callingCode: '+52', pattern: '^\\d{10}$' },
    { value: 'Micronesia', label: 'Micronesia', callingCode: '+691', pattern: '^\\d{7}$' },
    { value: 'Moldova', label: 'Moldova', callingCode: '+373', pattern: '^\\d{8}$' },
    { value: 'Monaco', label: 'Monaco', callingCode: '+377', pattern: '^\\d{8}$' },
    { value: 'Mongolia', label: 'Mongolia', callingCode: '+976', pattern: '^\\d{8}$' },
    { value: 'Montenegro', label: 'Montenegro', callingCode: '+382', pattern: '^\\d{8}$' },
    { value: 'Morocco', label: 'Morocco', callingCode: '+212', pattern: '^\\d{9}$' },
    { value: 'Myanmar', label: 'Myanmar', callingCode: '+95', pattern: '^\\d{8,9}$' },
    { value: 'Nepal', label: 'Nepal', callingCode: '+977', pattern: '^\\d{10}$' },
    { value: 'Netherlands', label: 'Netherlands', callingCode: '+31', pattern: '^\\d{9}$' },
    { value: 'New Zealand', label: 'New Zealand', callingCode: '+64', pattern: '^\\d{8,9}$' },
    { value: 'Nigeria', label: 'Nigeria', callingCode: '+234', pattern: '^\\d{10}$' },
    { value: 'North Korea', label: 'North Korea', callingCode: '+850', pattern: '^\\d{9}$' },
    { value: 'North Macedonia', label: 'North Macedonia', callingCode: '+389', pattern: '^\\d{8}$' },
    { value: 'Norway', label: 'Norway', callingCode: '+47', pattern: '^\\d{8}$' },
    { value: 'Oman', label: 'Oman', callingCode: '+968', pattern: '^\\d{8}$' },
    { value: 'Pakistan', label: 'Pakistan', callingCode: '+92', pattern: '^\\d{10}$' },
    { value: 'Palau', label: 'Palau', callingCode: '+680', pattern: '^\\d{7}$' },
    { value: 'Papua New Guinea', label: 'Papua New Guinea', callingCode: '+675', pattern: '^\\d{8}$' },
    { value: 'Peru', label: 'Peru', callingCode: '+51', pattern: '^\\d{9}$' },
    { value: 'Philippines', label: 'Philippines', callingCode: '+63', pattern: '^\\d{10}$' },
    { value: 'Poland', label: 'Poland', callingCode: '+48', pattern: '^\\d{9}$' },
    { value: 'Portugal', label: 'Portugal', callingCode: '+351', pattern: '^\\d{9}$' },
    { value: 'Qatar', label: 'Qatar', callingCode: '+974', pattern: '^\\d{8}$' },
    { value: 'Romania', label: 'Romania', callingCode: '+40', pattern: '^\\d{9}$' },
    { value: 'Russia', label: 'Russia', callingCode: '+7', pattern: '^\\d{10}$' },
    { value: 'San Marino', label: 'San Marino', callingCode: '+378', pattern: '^\\d{9}$' },
    { value: 'Saudi Arabia', label: 'Saudi Arabia', callingCode: '+966', pattern: '^\\d{9}$' },
    { value: 'Serbia', label: 'Serbia', callingCode: '+381', pattern: '^\\d{8,9}$' },
    { value: 'Singapore', label: 'Singapore', callingCode: '+65', pattern: '^\\d{8}$' },
    { value: 'Slovakia', label: 'Slovakia', callingCode: '+421', pattern: '^\\d{9}$' },
    { value: 'Slovenia', label: 'Slovenia', callingCode: '+386', pattern: '^\\d{8}$' },
    { value: 'Solomon Islands', label: 'Solomon Islands', callingCode: '+677', pattern: '^\\d{5}$' },
    { value: 'South Africa', label: 'South Africa', callingCode: '+27', pattern: '^\\d{9}$' },
    { value: 'South Korea', label: 'South Korea', callingCode: '+82', pattern: '^\\d{9,10}$' },
    { value: 'Spain', label: 'Spain', callingCode: '+34', pattern: '^\\d{9}$' },
    { value: 'Sri Lanka', label: 'Sri Lanka', callingCode: '+94', pattern: '^\\d{9}$' },
    { value: 'Sudan', label: 'Sudan', callingCode: '+249', pattern: '^\\d{9}$' },
    { value: 'Sweden', label: 'Sweden', callingCode: '+46', pattern: '^\\d{9}$' },
    { value: 'Switzerland', label: 'Switzerland', callingCode: '+41', pattern: '^\\d{9}$' },
    { value: 'Syria', label: 'Syria', callingCode: '+963', pattern: '^\\d{9}$' },
    { value: 'Tajikistan', label: 'Tajikistan', callingCode: '+992', pattern: '^\\d{9}$' },
    { value: 'Tanzania', label: 'Tanzania', callingCode: '+255', pattern: '^\\d{9}$' },
    { value: 'Thailand', label: 'Thailand', callingCode: '+66', pattern: '^\\d{9}$' },
    { value: 'Tunisia', label: 'Tunisia', callingCode: '+216', pattern: '^\\d{8}$' },
    { value: 'Turkey', label: 'Turkey', callingCode: '+90', pattern: '^\\d{10}$' },
    { value: 'Turkmenistan', label: 'Turkmenistan', callingCode: '+993', pattern: '^\\d{8}$' },
    { value: 'Tuvalu', label: 'Tuvalu', callingCode: '+688', pattern: '^\\d{5}$' },
    { value: 'Uganda', label: 'Uganda', callingCode: '+256', pattern: '^\\d{9}$' },
    { value: 'Ukraine', label: 'Ukraine', callingCode: '+380', pattern: '^\\d{9}$' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates', callingCode: '+971', pattern: '^\\d{9}$' },
    { value: 'United Kingdom', label: 'United Kingdom', callingCode: '+44', pattern: '^\\d{10}$' },
    { value: 'United States', label: 'United States', callingCode: '+1', pattern: '^\\d{10}$' },
    { value: 'Uzbekistan', label: 'Uzbekistan', callingCode: '+998', pattern: '^\\d{9}$' },
    { value: 'Vanuatu', label: 'Vanuatu', callingCode: '+678', pattern: '^\\d{5}$' },
    { value: 'Vatican City', label: 'Vatican City', callingCode: '+379', pattern: '^\\d{8}$' },
    { value: 'Venezuela', label: 'Venezuela', callingCode: '+58', pattern: '^\\d{10}$' },
    { value: 'Vietnam', label: 'Vietnam', callingCode: '+84', pattern: '^\\d{9,10}$' },
];
